### ISSUE TITLE
License GPL => LGPL

### ISSUE THREAD

**Issue by GermanBluefox** [PArns/ioBroker.amazon-dash#1]
Hello Patrick,
GPL license has strong copyleft effect, that means, every module in the whole software must be then GPL.
Theoretically even iobroker.js-controller. 
If no other dependency uses GPL, could you change the license from GPL to LGPLv3?

It is the same as GPL, but it allows to use module in other software.

Thanks,
Bluefox

**Comment by PArns** [comment]
Hi, you can even use GPL code in non GPL projects if it's not depending on it (otherwise noone for example Apple or Sony) would be able to use Linux within their products ;)

I've changed the license together with an requested update in the board.

I'll test the latest changes at home and will then release everything to npm
